Traceback (most recent call last):
  File "/Users/olles/miniconda3/envs/envone/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/olles/miniconda3/envs/envone/lib/python3.10/site-packages/nbclient/client.py", line 1265, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/olles/miniconda3/envs/envone/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/olles/miniconda3/envs/envone/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/olles/miniconda3/envs/envone/lib/python3.10/site-packages/nbclient/client.py", line 703, in async_execute
    await self.async_execute_cell(
  File "/Users/olles/miniconda3/envs/envone/lib/python3.10/site-packages/nbclient/client.py", line 1021, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/olles/miniconda3/envs/envone/lib/python3.10/site-packages/nbclient/client.py", line 915, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from data.passenger import get_passenger_data
from data.gold import get_gold_data
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdata[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpassenger[39;00m [38;5;28;01mimport[39;00m get_passenger_data
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdata[39;00m[38;5;21;01m.[39;00m[38;5;21;01mgold[39;00m [38;5;28;01mimport[39;00m get_gold_data

[0;31mModuleNotFoundError[0m: No module named 'data'
ModuleNotFoundError: No module named 'data'

